"""add issue country/state_code/assigned_to + staff_regions

Revision ID: 17bcc95440b9
Revises: 69cd75f0ba09
Create Date: 2025-10-26 09:10:48.680160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bcc95440b9'
down_revision: Union[str, Sequence[str], None] = '69cd75f0ba09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
