"""add issue country/state_code/assigned_to + staff_regions

Revision ID: 69cd75f0ba09
Revises: 06ac33bc88cc
Create Date: 2025-10-26 04:30:06.764393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69cd75f0ba09'
down_revision: Union[str, Sequence[str], None] = '06ac33bc88cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('issues', sa.Column('state_code', sa.String(length=3), nullable=True))
    op.create_index(op.f('ix_issues_assigned_to_id'), 'issues', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_issues_country'), 'issues', ['country'], unique=False)
    op.create_index(op.f('ix_issues_state_code'), 'issues', ['state_code'], unique=False)
    op.drop_constraint(op.f('issues_assigned_to_id_fkey'), 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'users', ['assigned_to_id'], ['id'])
    op.add_column('users', sa.Column('email_verify_code', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('email_verify_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verify_expires_at')
    op.drop_column('users', 'email_verify_code')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key(op.f('issues_assigned_to_id_fkey'), 'issues', 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_issues_state_code'), table_name='issues')
    op.drop_index(op.f('ix_issues_country'), table_name='issues')
    op.drop_index(op.f('ix_issues_assigned_to_id'), table_name='issues')
    op.drop_column('issues', 'state_code')
    op.drop_column('issues', 'country')
    # ### end Alembic commands ###
